### ISSUE TITLE
There is no test to ensure suitable interfaces are present for use

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-discoverable-services#10]
This was issue resin-io/bonjour#3.

The underlying reason for this was due to the network architecture being used. In that case, the use of iptables to redirect all traffic from `eth0` to `wlan0`. When `wlan0` was removed, `eth0` was not viewable (due to traffic redirection). This left only `lo`, which is pretty non-sensical.

A test is required to ensure that at least one non-loopback interface is present to bind to.

**Comment by lekkas** [comment]
> This left only lo, which is pretty non-sensical.
> A test is required to ensure that at least one non-loopback interface is present to bind to.

Why can't we use loopback for devenv discovery when we're only working on localhost and we are not interested in discovering devenv's hosted on other hosts present in the LAN?

**Comment by hedss** [comment]
Multicast on loopback is ... interesting. Whilst OSX allows it by default, Linux does not. Whilst that's not a massive deal, it does alter how users may expect it to work on varying platforms. This is the very reason @imrehg saw this issue. 

I was, in fact, in two minds about this when I added the check this morning, because we could just by default always apply multicast loopback which would remove the error, but might cause confusion on the part of a user.

Perhaps an explicit message in the README.md would mitigate this.

**Comment by hedss** [comment]
New issue, #12, added to perpetuate loopback multicast requirements.
